version: '2.2'

services:
  frontend:
    image: control-expense
    build: .
    ports:
      - "7005:7005"
    restart: on-failure
    container_name: control-expense
    volumes:
      - .:/app
      - /app/node_modules
